//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTester.HL7WebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://RUHealth.org/", ConfigurationName="HL7WebServices.HL7MessageReceiverSoap")]
    public interface HL7MessageReceiverSoap {
        
        // CODEGEN: Generating message contract since element name MessageType from namespace http://RUHealth.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://RUHealth.org/AddHL7MessageToWarehouse", ReplyAction="*")]
        WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseResponse AddHL7MessageToWarehouse(WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://RUHealth.org/AddHL7MessageToWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseResponse> AddHL7MessageToWarehouseAsync(WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHL7MessageToWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHL7MessageToWarehouse", Namespace="http://RUHealth.org/", Order=0)]
        public WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequestBody Body;
        
        public AddHL7MessageToWarehouseRequest() {
        }
        
        public AddHL7MessageToWarehouseRequest(WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://RUHealth.org/")]
    public partial class AddHL7MessageToWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MessageType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passphrase;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HL7Message;
        
        public AddHL7MessageToWarehouseRequestBody() {
        }
        
        public AddHL7MessageToWarehouseRequestBody(string MessageType, string Passphrase, string HL7Message) {
            this.MessageType = MessageType;
            this.Passphrase = Passphrase;
            this.HL7Message = HL7Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHL7MessageToWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHL7MessageToWarehouseResponse", Namespace="http://RUHealth.org/", Order=0)]
        public WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseResponseBody Body;
        
        public AddHL7MessageToWarehouseResponse() {
        }
        
        public AddHL7MessageToWarehouseResponse(WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://RUHealth.org/")]
    public partial class AddHL7MessageToWarehouseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddHL7MessageToWarehouseResult;
        
        public AddHL7MessageToWarehouseResponseBody() {
        }
        
        public AddHL7MessageToWarehouseResponseBody(string AddHL7MessageToWarehouseResult) {
            this.AddHL7MessageToWarehouseResult = AddHL7MessageToWarehouseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HL7MessageReceiverSoapChannel : WebServiceTester.HL7WebServices.HL7MessageReceiverSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HL7MessageReceiverSoapClient : System.ServiceModel.ClientBase<WebServiceTester.HL7WebServices.HL7MessageReceiverSoap>, WebServiceTester.HL7WebServices.HL7MessageReceiverSoap {
        
        public HL7MessageReceiverSoapClient() {
        }
        
        public HL7MessageReceiverSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HL7MessageReceiverSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HL7MessageReceiverSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HL7MessageReceiverSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseResponse WebServiceTester.HL7WebServices.HL7MessageReceiverSoap.AddHL7MessageToWarehouse(WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequest request) {
            return base.Channel.AddHL7MessageToWarehouse(request);
        }
        
        public string AddHL7MessageToWarehouse(string MessageType, string Passphrase, string HL7Message) {
            WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequest inValue = new WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequest();
            inValue.Body = new WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequestBody();
            inValue.Body.MessageType = MessageType;
            inValue.Body.Passphrase = Passphrase;
            inValue.Body.HL7Message = HL7Message;
            WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseResponse retVal = ((WebServiceTester.HL7WebServices.HL7MessageReceiverSoap)(this)).AddHL7MessageToWarehouse(inValue);
            return retVal.Body.AddHL7MessageToWarehouseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseResponse> WebServiceTester.HL7WebServices.HL7MessageReceiverSoap.AddHL7MessageToWarehouseAsync(WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequest request) {
            return base.Channel.AddHL7MessageToWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseResponse> AddHL7MessageToWarehouseAsync(string MessageType, string Passphrase, string HL7Message) {
            WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequest inValue = new WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequest();
            inValue.Body = new WebServiceTester.HL7WebServices.AddHL7MessageToWarehouseRequestBody();
            inValue.Body.MessageType = MessageType;
            inValue.Body.Passphrase = Passphrase;
            inValue.Body.HL7Message = HL7Message;
            return ((WebServiceTester.HL7WebServices.HL7MessageReceiverSoap)(this)).AddHL7MessageToWarehouseAsync(inValue);
        }
    }
}
